#!/bin/bash

# if first argument exists set it as the url/search query
if [ "$1" ]; then
	query=$1
fi

# if first argument doesn't exist prompt the user for url/search query
if [ -z $1 ]; then
	query=$(fuzzel --dmenu -l 0 -p "Search YouTube: " <&- | tr ' ' '+')
fi

# exit if query is empty
if [ -z $query ]; then exit 0; fi

urlSubstring="https://"

if [[ $query =~ $urlSubstring ]]; then
        maxres=$(echo -e "144\n240\n360\n480\n720\n1080\nExit" | fuzzel --dmenu -i -l 7 -p "Choose a resolution: ")

        # exit if user did not pick a resolution
        if [ -z $maxres ]; then exit 0; fi
        if [[ $maxres == "Exit" ]]; then exit 0; fi

        notify-send --app-name="YT" "Loading video"
        mpv "$query" --ytdl-format="bestvideo[height<=?"$maxres"]+bestaudio/best"
else
        notify-send --app-name="YT" "Searching for videos..."
        curl -s "https://yewtu.be/search?q=%$query" > ".temp-yt.html"
        cachedpage='cat ./.temp-yt.html'
        vidlist=$( $cachedpage | grep -Eo "watch\?v=.{11}")

	declare -A titlearr
        titlelist=''

        for i in $vidlist
        do
            title="["`$cachedpage | pup 'a[href="/'$i'"] + div p.channel-name text{}'`"] "`$cachedpage | pup 'a[href="/'$i'"] > p text{}'`""

	    # render ampersands properly
	    title="${title/'&amp;'/'&'}"
	    title="${title/'&#34;'/\"}"
	    title="${title/'&#39;'/\'}"

	    titlearr[$title]=$i
	    
            if ! [[ $titlelist =~ $i ]]
            then
                titlelist=$titlelist"\n"$title
            fi
        done
	
	echo ${!titlearr[@]}

	# sed command strips out empty lines
        # vid=$(echo -e $titlelist | uniq | sed '/^[[:space:]]*$/d' | fuzzel --dmenu -i -l 25 -p "Choose a video to watch: " | awk 'BEGIN { FS = "\t" } ; {print $2}')
        vid=$(echo -e $titlelist | uniq | sed '/^[[:space:]]*$/d' | fuzzel --dmenu -i -l 25 -p "Choose a video to watch: ")
	urlpart=${titlearr[$vid]}
	echo $urlpart
	
        # exit if user did not pick a video
        if [ -z $urlpart ]; then exit 0; fi

        url="https://youtube.com/$urlpart"

        rm "./.temp-yt.html"

        maxres=$(echo -e "144\n240\n360\n480\n720\n1080\nExit" | fuzzel --dmenu -i -l 7 -p "Choose a resolution: ")
        # exit if user did not pick a resolution
        if [ -z $maxres ]; then exit 0; fi
        if [[ $maxres == "Exit" ]]; then exit 0; fi

        notify-send --app-name="YT" "Loading video..."
        mpv "$url" --ytdl-format="bestvideo[height<=?"$maxres"]+bestaudio/best"
fi
