#!/bin/bash

query=$(printf '%s' "$*" | tr ' ' '+')
curl -s "https://yewtu.be/search?q=%$query" > ".temp-yt.html"
cachedpage='cat ./.temp-yt.html'
vidlist=$( $cachedpage | grep -Eo "watch\?v=.{11}")

titlelist=''

for i in $vidlist
do
	title="["`$cachedpage | pup 'a[href="/'$i'"] + div p.channel-name text{}'`"] "`$cachedpage | pup 'a[href="/'$i'"] > p text{}'`"\t\t$i"
	if ! [[ $titlelist =~ $i ]]
	then 
		titlelist=$titlelist"\n"$title
	fi
done

vid=$(echo -e $titlelist | uniq | fzf | awk 'BEGIN { FS = "\t\t" } ; {print $2}')

url="https://youtube.com/$vid"

rm "./.temp-yt.html"
mpv "$url"

